[project]
name = "mwl-provider"
version = "0.1.0"
description = "DICOM Modality Worklist Provider"
authors = []
dependencies = [
    "fhir.resources",
    "fastapi",
    "pydicom",
    "pynetdicom",
    "sqlalchemy",
    "alembic",
    "flask-admin",
    "flask-sqlalchemy",
    "wtforms-sqlalchemy",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "invoke",
    "build",
    "wheel",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
