"""empty message

Revision ID: 22359b8eaba0
Revises: 7a3986ac5aae
Create Date: 2024-11-18 20:15:02.791405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22359b8eaba0'
down_revision: Union[str, None] = '7a3986ac5aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add temporary columns
    op.add_column('requested_procedures', sa.Column('name_temp', sa.String(), nullable=False, server_default='Unnamed Protocol'))
    op.add_column('scheduled_procedure_steps', sa.Column('name_temp', sa.String(), nullable=False, server_default='Unnamed Protocol'))
    op.add_column('scheduled_protocols', sa.Column('name_temp', sa.String(), nullable=False, server_default='Unnamed Protocol'))

    # Update temporary columns with data from original columns
    op.execute('UPDATE requested_procedures SET name_temp = name')
    op.execute('UPDATE scheduled_procedure_steps SET name_temp = name')
    op.execute('UPDATE scheduled_protocols SET name_temp = name')

    # Drop original columns
    with op.batch_alter_table('requested_procedures') as batch_op:
        batch_op.drop_column('name')
    with op.batch_alter_table('scheduled_procedure_steps') as batch_op:
        batch_op.drop_column('name')
    with op.batch_alter_table('scheduled_protocols') as batch_op:
        batch_op.drop_column('name')

    # Rename temporary columns to original column names
    with op.batch_alter_table('requested_procedures') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name', server_default=None)
    with op.batch_alter_table('scheduled_procedure_steps') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name', server_default=None)
    with op.batch_alter_table('scheduled_protocols') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add original columns back
    op.add_column('requested_procedures', sa.Column('name_temp', sa.String(), nullable=True))
    op.add_column('scheduled_procedure_steps', sa.Column('name_temp', sa.String(), nullable=True))
    op.add_column('scheduled_protocols', sa.Column('name_temp', sa.String(), nullable=True))

    # Update original columns with data from temporary columns
    op.execute('UPDATE requested_procedures SET name_temp = name')
    op.execute('UPDATE scheduled_procedure_steps SET name_temp = name')
    op.execute('UPDATE scheduled_protocols SET name_temp = name')

    # Drop temporary columns
    with op.batch_alter_table('requested_procedures') as batch_op:
        batch_op.drop_column('name')
    with op.batch_alter_table('scheduled_procedure_steps') as batch_op:
        batch_op.drop_column('name')
    with op.batch_alter_table('scheduled_protocols') as batch_op:
        batch_op.drop_column('name')

    # Rename original columns back to original names
    with op.batch_alter_table('requested_procedures') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name')
    with op.batch_alter_table('scheduled_procedure_steps') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name')
    with op.batch_alter_table('scheduled_protocols') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name')
    # ### end Alembic commands ###
