"""empty message

Revision ID: 34cb58afec56
Revises: 22359b8eaba0
Create Date: 2024-11-18 22:22:36.696274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cb58afec56'
down_revision: Union[str, None] = '22359b8eaba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new column
    op.add_column('external_procedures', sa.Column('name_temp', sa.String(), nullable=False, server_default='Unnamed External Procedure'))

    # Update the new column with data from the old column
    op.execute('UPDATE external_procedures SET name_temp = name')

    # Drop the old column
    with op.batch_alter_table('external_procedures') as batch_op:
        batch_op.drop_column('name')

    # Rename the new column to the old column name
    with op.batch_alter_table('external_procedures') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the old column back
    op.add_column('external_procedures', sa.Column('name_temp', sa.String(), nullable=True))

    # Update the old column with data from the new column
    op.execute('UPDATE external_procedures SET name_temp = name')

    # Drop the new column
    with op.batch_alter_table('external_procedures') as batch_op:
        batch_op.drop_column('name')

    # Rename the old column back to the new column name
    with op.batch_alter_table('external_procedures') as batch_op:
        batch_op.alter_column('name_temp', new_column_name='name')
    # ### end Alembic commands ###
