"""Initial database setup

Revision ID: 7a3986ac5aae
Revises: 
Create Date: 2024-11-18 19:39:26.328349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3986ac5aae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'requested_procedures',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('code_value', sa.String),
        sa.Column('code_scheme', sa.String),
        sa.Column('code_meaning', sa.String),
        sa.Column('name', sa.String),
        sa.Column('comments', sa.String),
        sa.Column('description', sa.String),
        sa.Column('requesting_physician_name', sa.String)
    )

    op.create_table(
        'scheduled_procedure_steps',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String),
        sa.Column('start_date', sa.Date),
        sa.Column('start_time', sa.Time),
        sa.Column('modality', sa.String),
        sa.Column('station_ae_title', sa.String),
        sa.Column('code_value', sa.String),
        sa.Column('code_scheme', sa.String),
        sa.Column('code_meaning', sa.String),
        sa.Column('location', sa.String),
        sa.Column('performing_physicians_name', sa.String)
    )

    op.create_table(
        'scheduled_protocols',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('code_value', sa.String),
        sa.Column('code_scheme', sa.String),
        sa.Column('code_meaning', sa.String),
        sa.Column('name', sa.String)
    )

    op.create_table(
        'scheduled_protocols_association',
        sa.Column('procedure_step_id', sa.Integer, sa.ForeignKey('scheduled_procedure_steps.id')),
        sa.Column('protocol_id', sa.Integer, sa.ForeignKey('scheduled_protocols.id'))
    )

    op.create_table(
        'requested_procedure_steps_association',
        sa.Column('requested_procedure_id', sa.Integer, sa.ForeignKey('requested_procedures.id')),
        sa.Column('procedure_step_id', sa.Integer, sa.ForeignKey('scheduled_procedure_steps.id'))
    )

    op.create_table(
        'external_procedures',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('system', sa.String),
        sa.Column('code', sa.String),
        sa.Column('name', sa.String),
        sa.Column('description', sa.String),
        sa.Column('short_name', sa.String),
        sa.Column('requested_procedure_id', sa.Integer, sa.ForeignKey('requested_procedures.id'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_procedures')
    op.drop_table('requested_procedure_steps_association')
    op.drop_table('scheduled_protocols_association')
    op.drop_table('scheduled_protocols')
    op.drop_table('scheduled_procedure_steps')
    op.drop_table('requested_procedures')
    # ### end Alembic commands ###
